version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - dataprod:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - app-network

  api:
    volumes:
      - dataprod:/data
    environment:
      - DEBUG=1
      - PRODUCTION=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - db.env
    depends_on:
      - db
    ports:
      - 9001:9001
    networks:
      app-network:
        aliases:
          - api

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx-test:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
    networks:
      - app-network

volumes:
  dataprod:
    # external: true
  
networks:
  app-network:
    # external: true
    driver: bridge
    name: app-network
