version: '3.8'
    
services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - db-volume:/var/lib/postgres
  #   networks:
  #     - app-network
  # redis:
  #   image: redis:5
  #   networks:
  #         - app-network
  app:
    build: .
    # command: python manage.py runserver 0.0.0.0:8001 
    # command: supervisord -c supervisord.conf -n
    command: >
      sh -c "(cd /code/frontend && npm install)
      && (cd /code/frontend && npm run build)
      && python manage.py runserver 0.0.0.0:9000"

    image: playlistener
    # restart: unless-stopped
    # tty: true
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    # depends_on:
    #   - redis
    # working_dir: /code
    networks:
      - app-network


# volumes:
#   db-volume: 

networks:
  app-network:
    driver: bridge

