version: '3.8'
    
services:
  app:
    image: playlistener-api
    build: 
      context: .
    # command: python manage.py runserver 0.0.0.0:9002
    volumes:
      - .:/code
    ports:
      - "9000:9000"    
      - "9001:9001"
      - "9002:9002"

