version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - devdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

  api:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:9002
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY='m925%@rztqnd=%6l9neo!h2w=ro_iaw-uryy!jlsdvrmnl-qie'
    depends_on:
      - db
    ports:
      - "9000:9000"    
      - "9001:9001"
      - "9002:9002"
    
volumes:
  devdata:
