version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    networks:
      playlistener-network:    

  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY='m925%@rztqnd=%6l9neo!h2w=ro_iaw-uryy!jlsdvrmnl-qie'
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      playlistener-network:    
        aliases:
          - playlistenerapi

networks:
  playlistener-network:
    external: true
    driver: bridge
    name: playlistener-network