version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - dataprod:/var/lib/postgresql/data
    env_file:
      - prod.env
    networks:
      - app-network

  api:
    volumes:
      - dataprod:/data
    environment:
      - DEBUG=0
      - PRODUCTION=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - prod.env
    depends_on:
      - db
    networks:
      app-network:
        aliases:
          - api

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - dataprod:/data
    ports:
      - 8000:8000
    networks:
      - app-network

volumes:
  dataprod:
    external: true
  
networks:
  app-network:
    driver: bridge
    name: app-network
