version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - dataprod:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      playlistener-network:

  app:
    volumes:
      - dataprod:/data
      - webassets:/var/www/html
    environment:
      - DEBUG=0
      - PRODUCTION=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    depends_on:
      - db
    networks:
      playlistener-network:

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - webassets:/var/www/html:ro
    networks:
      playlistener-network:    
        aliases:
          - playlistenerapi
    ports:
      - 8000:8000
    depends_on:
      - app

volumes:
  dataprod:
    external: true
  webassets: 

networks:
  playlistener-network:
    external: true
    driver: bridge
    name: playlistener-network
