# Generated by Django 3.2.15 on 2022-09-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaresource',
            old_name='converted_432_duration',
            new_name='audiofile_432_duration',
        ),
        migrations.RenameField(
            model_name='mediaresource',
            old_name='original_duration',
            new_name='audiofile_duration',
        ),
    ]
