apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: plapi
spec:
  selector:
    app: app
  ports:
  - name: app
    protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: plapi
spec:
  selector:
    app: db
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432